# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 13:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignupDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(blank=True, max_length=120, null=True)),
                ('country_id', models.IntegerField(blank=True, null=True)),
                ('role', models.IntegerField(blank=True, null=True)),
                ('title', models.IntegerField(blank=True, null=True)),
                ('dr_licence', models.CharField(blank=True, max_length=25, null=True)),
                ('ph_licence', models.CharField(blank=True, max_length=25, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
