# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 08:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ldn_app', '0002_patientdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('1-20', '1-20'), ('21-50', '21-50'), ('51-100', '51-100')], default='1-20', max_length=10)),
                ('amount', models.IntegerField()),
                ('transaction_no', models.CharField(default='none', max_length=30)),
                ('transaction_date', models.DateTimeField(default=datetime.datetime(2017, 12, 21, 13, 59, 54, 260000))),
                ('transaction_status', models.CharField(choices=[('NONE', 'NONE'), ('SUCCESS', 'SUCCESS'), ('PENDING', 'PENDING'), ('REFUND', 'REFUND'), ('CANCELLED', 'CANCELLED')], default='NONE', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
