# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 08:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldn_app', '0003_paypaltransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypaltransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='paypaltransaction',
            name='subscription_type',
            field=models.CharField(choices=[('UNLIMITED', 'UNLIMITED'), ('1-20', '1-20'), ('21-50', '21-50'), ('51-100', '51-100')], default='1-20', max_length=10),
        ),
        migrations.AlterField(
            model_name='paypaltransaction',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 28, 14, 6, 32, 480000)),
        ),
        migrations.AlterField(
            model_name='paypaltransaction',
            name='transaction_status',
            field=models.CharField(choices=[('NONE', 'NONE'), ('COMPLETED', 'COMPLETED'), ('PENDING', 'PENDING'), ('REFUND', 'REFUND'), ('CANCELLED', 'CANCELLED')], default='NONE', max_length=15),
        ),
    ]
